`timescale 1ns / 1ps
// =============================================================================
// tb_ecg_all_records.sv
//
// Testbench that iterates over all 48 MIT-BIH Arrhythmia Database records,
// runs the full ECG pipeline for each, and writes results to results.csv.
//
// CSV columns:
//   record, d4_count, qrs_count, r_loc_count, last_hr_bpm, r_peak_samples
//
// Usage (ModelSim / QuestaSim):
//   do run_all_records.do
//
// Requirements:
//   • All 48 .mem files in the working directory (generated by generate_mem_files.py)
//   • All RTL source files compiled
// =============================================================================

module tb_ecg_all_records;

    // -------------------------------------------------------------------------
    // Parameters
    // -------------------------------------------------------------------------
    localparam WIDTH    = 16;
    localparam N        = 3000;
    localparam CLK_HALF = 5;    // 100 MHz

    // Safe timeout per record (cycles).
    // DWT: ~2813 + QRS: ~187 + r_loc: 10 beats × 90 samples × 3 cyc = 2700
    // → ~6000 cycles minimum. 30000 gives 5× margin for slow HR records.
    localparam TIMEOUT_CYCLES = 30000;

    // -------------------------------------------------------------------------
    // Clock & DUT signals
    // -------------------------------------------------------------------------
    logic clk = 0;
    logic rst;
    always #CLK_HALF clk = ~clk;

    logic [11:0] true_r_location;
    logic        r_location_valid;
    logic [7:0]  heart_rate_bpm;
    logic        hr_valid;

    // -------------------------------------------------------------------------
    // DUT — single instance reused across all records via $readmemh
    // -------------------------------------------------------------------------
    ecg_system_top #(
        .WIDTH   (WIDTH),
        .N       (N),
        .MEM_FILE("100.mem")    // default; overridden per-record below
    ) dut (
        .clk             (clk),
        .rst             (rst),
        .true_r_location (true_r_location),
        .r_location_valid(r_location_valid),
        .heart_rate_bpm  (heart_rate_bpm),
        .hr_valid        (hr_valid)
    );

    // -------------------------------------------------------------------------
    // Per-record counters and result storage
    // -------------------------------------------------------------------------
    integer d4_count, qrs_count, r_loc_count;
    integer last_hr;

    // Up to 64 R-peak locations per record
    localparam MAX_PEAKS = 64;
    integer peak_buf [0:MAX_PEAKS-1];
    integer peak_idx;

    // Monitor d4_count via internal hierarchy
    logic d4_valid_mon;
    logic peak_valid_mon;
    assign d4_valid_mon   = dut.d4_valid;
    assign peak_valid_mon = dut.peak_valid;

    // -------------------------------------------------------------------------
    // MIT-BIH record list (all 48 records)
    // -------------------------------------------------------------------------
    // Records are stored as integers; formatted to "NNN.mem" strings at runtime.
    integer rec_list [0:47];
    string  mem_filename;
    integer csv_fd;
    integer rec_num;
    integer i;
    integer cyc;

    initial begin
        // Populate record list
        rec_list[0]  = 100; rec_list[1]  = 101; rec_list[2]  = 102;
        rec_list[3]  = 103; rec_list[4]  = 104; rec_list[5]  = 105;
        rec_list[6]  = 106; rec_list[7]  = 107; rec_list[8]  = 108;
        rec_list[9]  = 109; rec_list[10] = 111; rec_list[11] = 112;
        rec_list[12] = 113; rec_list[13] = 114; rec_list[14] = 115;
        rec_list[15] = 116; rec_list[16] = 117; rec_list[17] = 118;
        rec_list[18] = 119; rec_list[19] = 121; rec_list[20] = 122;
        rec_list[21] = 123; rec_list[22] = 124; rec_list[23] = 200;
        rec_list[24] = 201; rec_list[25] = 202; rec_list[26] = 203;
        rec_list[27] = 205; rec_list[28] = 207; rec_list[29] = 208;
        rec_list[30] = 209; rec_list[31] = 210; rec_list[32] = 212;
        rec_list[33] = 213; rec_list[34] = 214; rec_list[35] = 215;
        rec_list[36] = 217; rec_list[37] = 219; rec_list[38] = 220;
        rec_list[39] = 221; rec_list[40] = 222; rec_list[41] = 223;
        rec_list[42] = 228; rec_list[43] = 230; rec_list[44] = 231;
        rec_list[45] = 232; rec_list[46] = 233; rec_list[47] = 234;

        // Open CSV
        csv_fd = $fopen("results.csv", "w");
        if (csv_fd == 0) begin
            $display("ERROR: cannot open results.csv for writing");
            $finish;
        end
        $fwrite(csv_fd, "record,d4_count,qrs_count,r_loc_count,last_hr_bpm,r_peak_samples\n");

        // ----------------------------------------------------------------
        // Iterate over all 48 records
        // ----------------------------------------------------------------
        for (i = 0; i < 48; i++) begin
            rec_num = rec_list[i];
            $sformat(mem_filename, "%0d.mem", rec_num);

            // Load .mem file into DUT's internal ROM via hierarchical path
            $readmemh(mem_filename, dut.ecg_rom);
            $display("Record %0d: loaded %s", rec_num, mem_filename);

            // Reset counters
            d4_count   = 0;
            qrs_count  = 0;
            r_loc_count = 0;
            last_hr    = 0;
            peak_idx   = 0;

            // Assert reset for 4 clock cycles
            rst = 1;
            repeat(4) @(posedge clk);
            @(negedge clk);
            rst = 0;

            // Run for TIMEOUT_CYCLES cycles, sampling outputs each cycle
            for (cyc = 0; cyc < TIMEOUT_CYCLES; cyc++) begin
                @(posedge clk);
                #1; // Small delta to let outputs settle

                // Count d4 outputs
                if (dut.d4_valid)
                    d4_count = d4_count + 1;

                // Count QRS detections
                if (dut.peak_valid)
                    qrs_count = qrs_count + 1;

                // Capture R-peak locations
                if (r_location_valid) begin
                    r_loc_count = r_loc_count + 1;
                    if (peak_idx < MAX_PEAKS)
                        peak_buf[peak_idx++] = true_r_location;
                end

                // Capture latest HR
                if (hr_valid)
                    last_hr = heart_rate_bpm;
            end

            // Write CSV row
            // Format: record,d4_count,qrs_count,r_loc_count,last_hr_bpm,"p1 p2 p3..."
            $fwrite(csv_fd, "%0d,%0d,%0d,%0d,%0d,\"",
                    rec_num, d4_count, qrs_count, r_loc_count, last_hr);
            for (int p = 0; p < peak_idx; p++) begin
                if (p > 0) $fwrite(csv_fd, " ");
                $fwrite(csv_fd, "%0d", peak_buf[p]);
            end
            $fwrite(csv_fd, "\"\n");

            $display("  → d4=%0d  qrs=%0d  r_locs=%0d  hr=%0d BPM",
                     d4_count, qrs_count, r_loc_count, last_hr);
        end

        $fclose(csv_fd);
        $display("\nAll 48 records complete. Results written to results.csv");
        $finish;
    end

endmodule
